all: myshell

myshell: myshell.o LineParser.o
	gcc -m32 -g -Wall -o myshell myshell.o LineParser.o
	
myshell.o: myshell.c
	gcc -g -Wall -m32 -ansi -c -o myshell.o myshell.c
	
LineParser.o: LineParser.c
	gcc -g -Wall -m32 -ansi -c -o LineParser.o LineParser.c
	
clean: 
	rm -f *.o myshell